# Generated by Django 3.0.2 on 2020-03-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='time_to_report',
            field=models.PositiveIntegerField(choices=[(1, 'Icyumweru'), (2, 'Ukwezi'), (3, 'Igihembwe'), (4, 'Amezi atandatu'), (5, 'Umwaka')], default=1),
            preserve_default=False,
        ),
    ]
